---
title: "Codebook"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Description of the datasets and variables used in this project

#### Downloaded datasets

activity_labels.txt

  * activity code
  
    1. WALKING
    2. WALKING_UPSTAIRS
    3. WALKING_DOWNSTAIRS
    4. SITTING
    5. STANDING
    6. LAYING
    
features.txt

  * list of the 561 variables which are the combination of the following 2 sets of variables:
  
    * Set 1: signals acquired by the smartphone. 't' means time, 'f' means frequency. '-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.
        * tBodyAcc-XYZ
        * tGravityAcc-XYZ
        * tBodyAccJerk-XYZ
        * tBodyGyro-XYZ
        * tBodyGyroJerk-XYZ
        * tBodyAccMag
        * tGravityAccMag
        * tBodyAccJerkMag
        * tBodyGyroMag
        * tBodyGyroJerkMag
        * fBodyAcc-XYZ
        * fBodyAccJerk-XYZ
        * fBodyGyro-XYZ
        * fBodyAccMag
        * fBodyAccJerkMag
        * fBodyGyroMag
        * fBodyGyroJerkMag
    * Set 2: measurements estimated from these signals
        * mean(): Mean value
        * std(): Standard deviation
        * mad(): Median absolute deviation 
        * max(): Largest value in array
        * min(): Smallest value in array
        * sma(): Signal magnitude area
        * energy(): Energy measure. Sum of the squares divided by the number of values. 
        * iqr(): Interquartile range 
        * entropy(): Signal entropy
        * arCoeff(): Autorregresion coefficients with Burg order equal to 4
        * correlation(): correlation coefficient between two signals
        * maxInds(): index of the frequency component with largest magnitude
        * meanFreq(): Weighted average of the frequency components to obtain a mean frequency
        * skewness(): skewness of the frequency domain signal 
        * kurtosis(): kurtosis of the frequency domain signal 
        * bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
        * angle(): Angle between to vectors.

subject_test.txt

  * test participants. Each row represent a participant identified by a number from 1 to 30.
  
X_test.txt

  * dataset containing the test measured values
  
y_test.txt

  * test activities. Each row represent an activity and is identified by a number (see activity_labels.txt)
  
subject_train.txt

  * training participants. Each row represent a participant identified by a number from 1 to 30.
  
X_train.txt

  * dataset containing the training measured values
  
y_train.txt

  * training activities. Each row represent an activity and is identified by a number (see activity_labels.txt)
  
#### Dataset generated for the assessment

summary_set.csv

  * activityName
    * WALKING
    * WALKING_UPSTAIRS
    * WALKING_DOWNSTAIRS
    * SITTING
    * STANDING
    * LAYING
  * participantId: Each row represent a participant identified by a number from 1 to 30
  * columns with the average of each variable grouped by activity and participant
    * variables are the combination of the following 2 sets of variables:
    * Set 1: signals acquired by the smartphone. 't' means time, 'f' means frequency. '-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.
        * tBodyAcc-XYZ
        * tGravityAcc-XYZ
        * tBodyAccJerk-XYZ
        * tBodyGyro-XYZ
        * tBodyGyroJerk-XYZ
        * tBodyAccMag
        * tGravityAccMag
        * tBodyAccJerkMag
        * tBodyGyroMag
        * tBodyGyroJerkMag
        * fBodyAcc-XYZ
        * fBodyAccJerk-XYZ
        * fBodyGyro-XYZ
        * fBodyAccMag
        * fBodyAccJerkMag
        * fBodyGyroMag
        * fBodyGyroJerkMag
    * Set 2: measurements estimated from these signals
        * mean(): Mean value
        * std(): Standard deviation
        
### Explanation of the R script
1. Setting the working directory
2. Loading packages used in this script
3. Downloading and unzipping the datasets necessary for the assessment
    * checking the content of the download folders
4. Reading the datasets used for the assessment and assign them to specific R objects
5. Setting the column names in the data frames because the original datasets have no headers
    * activity_lbl, test_partic, test_activity, train_partic and train_activity were assigned descriptive column names
    * the column names for test_set and train_set were taken from the feature.txt dataset
6. Merging datasets
    * merging test_partic + test_activity + test_set to generate a test data frame with the participant Ids, the activity Ids and the measured test values (test_merge)
    * merging train_partic + train_activity + train_set to generate a test data frame with the participant Ids, the activity Ids and the measured training values (test_train)
    * merging test_merge + test_train to generate a combined data frame (train_test_df)
7. Extracting the columns containing means and standard deviations
    * some of the columns extracted contain the word 'mean', but they do not contain the data needed for the assessment, so they were removed
8. Adding a column with the explanatory names of the activities (activityName)
9. Replacing the dash sign with underscores and removing the parenthesis from column names. Parenthesis are not necessary there. Dashes in the names were generating errors in the next step. Column names were replaced with more explanatory names because that would have created unnecessarily long headers. This codebook and the original downloaded files explain those names in detail
10. Removing the column where activity was represented by a number (activityId), and reordering the columns so that the column activityName is now the second column
11. Generating the independent tidy data set with the average of each variable for each activity and each subject. In this data frame, grouping was done on activity and on participant within activity. Some of the variables have three measurements, one per axis (XYZ), and were kept separated as discreet sets of observations.
12. Generating a csv file with the data frame